/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.calculadorajava;

/**
 *
 * @author mario
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    
    char operacao;
    String temp, numeroAntes, copia;
    double num1, num2, resultado;
    
    public calc() {
        initComponents();
    }
    
    private void numeroDigitado(String numero) {
        temp = jTVisor.getText();
        numeroAntes = temp; //botão bsp.
        temp = temp + numero;
        jTVisor.setText(temp); 
    }
    
    private void escolheOperacao(char op) throws NumberFormatException {
        operacao = op;
        num1 = Double.parseDouble(jTVisor.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTVisor = new javax.swing.JTextField();
        jBbsp = new javax.swing.JButton();
        jBsete = new javax.swing.JButton();
        jBquatro = new javax.swing.JButton();
        jBum = new javax.swing.JButton();
        jBzero = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jBclr = new javax.swing.JButton();
        jBmm = new javax.swing.JButton();
        jBoito = new javax.swing.JButton();
        jBcinco = new javax.swing.JButton();
        jBdois = new javax.swing.JButton();
        jBponto = new javax.swing.JButton();
        jBnove = new javax.swing.JButton();
        jBseis = new javax.swing.JButton();
        jBtres = new javax.swing.JButton();
        jBigual = new javax.swing.JButton();
        jBdividir = new javax.swing.JButton();
        jBvezes = new javax.swing.JButton();
        jBmais = new javax.swing.JButton();
        jBmenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jBbsp.setText("BSP");
        jBbsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbspActionPerformed(evt);
            }
        });

        jBsete.setText("7");
        jBsete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseteActionPerformed(evt);
            }
        });

        jBquatro.setText("4");
        jBquatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBquatroActionPerformed(evt);
            }
        });

        jBum.setText("1");
        jBum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBumActionPerformed(evt);
            }
        });

        jBzero.setText("0");
        jBzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBzeroActionPerformed(evt);
            }
        });

        jButton6.setText("CE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jBclr.setText("CLR");
        jBclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclrActionPerformed(evt);
            }
        });

        jBmm.setText("-+");
        jBmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmmActionPerformed(evt);
            }
        });

        jBoito.setText("8");
        jBoito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoitoActionPerformed(evt);
            }
        });

        jBcinco.setText("5");
        jBcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcincoActionPerformed(evt);
            }
        });

        jBdois.setText("2");
        jBdois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdoisActionPerformed(evt);
            }
        });

        jBponto.setText(".");
        jBponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpontoActionPerformed(evt);
            }
        });

        jBnove.setText("9");
        jBnove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnoveActionPerformed(evt);
            }
        });

        jBseis.setText("6");
        jBseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseisActionPerformed(evt);
            }
        });

        jBtres.setText("3");
        jBtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtresActionPerformed(evt);
            }
        });

        jBigual.setText("=");
        jBigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBigualActionPerformed(evt);
            }
        });

        jBdividir.setText("/");
        jBdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdividirActionPerformed(evt);
            }
        });

        jBvezes.setText("X");
        jBvezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvezesActionPerformed(evt);
            }
        });

        jBmais.setText("+");
        jBmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmaisActionPerformed(evt);
            }
        });

        jBmenos.setText("-");
        jBmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTVisor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBum, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jBzero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBponto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBdois, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBcinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBbsp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBsete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jBoito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBnove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBclr, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBmm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBvezes, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jBmais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jBmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBdividir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jBbsp)
                    .addComponent(jBclr)
                    .addComponent(jBmm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBdividir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBnove)
                        .addComponent(jBoito)
                        .addComponent(jBsete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBseis)
                    .addComponent(jBvezes)
                    .addComponent(jBcinco)
                    .addComponent(jBquatro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBmais)
                            .addComponent(jBtres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBigual)
                            .addComponent(jBmenos)
                            .addComponent(jBponto)
                            .addComponent(jBzero)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBum)
                        .addComponent(jBdois, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmmActionPerformed
        if (temp.startsWith("-")){
            temp = temp.replace('-','+');
        } else if (temp.startsWith("+")) {
            temp = temp.replace('+','-');
        } else{
            temp = "+" + temp;
        }
        
        jTVisor.setText(temp);
    }//GEN-LAST:event_jBmmActionPerformed

    private void jBigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBigualActionPerformed
         num2 = Double.parseDouble(jTVisor.getText());
            switch (operacao) {
                case '+': 
                    resultado = num1 + num2; 
                    break;
                case '-':
                    resultado = num1 - num2; 
                    break;
                case 'X':
                    resultado = num1 * num2; 
                    break;
                case '/':
                    resultado = num1 / num2; 
                    break;
        } 
        jTVisor.setText(String.valueOf(resultado));
        numeroDigitado("2");
    }//GEN-LAST:event_jBigualActionPerformed

    private void jBpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpontoActionPerformed
        numeroDigitado(".");
    }//GEN-LAST:event_jBpontoActionPerformed

    private void jBcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcincoActionPerformed
        numeroDigitado("5");
    }//GEN-LAST:event_jBcincoActionPerformed

    private void jBbspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbspActionPerformed
        num2 = 0;
        jTVisor.setText(String.valueOf(num1));
    }//GEN-LAST:event_jBbspActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        num2 = 0;
        jTVisor.setText(String.valueOf(num1));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclrActionPerformed
        num1 = 0;
        num2 = 0;
        jTVisor.setText("");
    }//GEN-LAST:event_jBclrActionPerformed

    private void jBdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdividirActionPerformed
        escolheOperacao('/');
        jTVisor.setText("");
    }//GEN-LAST:event_jBdividirActionPerformed

    private void jBvezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvezesActionPerformed
        escolheOperacao('X');
        jTVisor.setText("");
    }//GEN-LAST:event_jBvezesActionPerformed

    private void jBmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmaisActionPerformed
        escolheOperacao('+');
        jTVisor.setText("");
    }//GEN-LAST:event_jBmaisActionPerformed

    private void jBmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmenosActionPerformed
        escolheOperacao('-');
        jTVisor.setText("");
    }//GEN-LAST:event_jBmenosActionPerformed

    private void jBzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBzeroActionPerformed
        numeroDigitado("0");
    }//GEN-LAST:event_jBzeroActionPerformed

    private void jBumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBumActionPerformed
        numeroDigitado("1");
    }//GEN-LAST:event_jBumActionPerformed

    private void jBdoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdoisActionPerformed
        numeroDigitado("2");
    }//GEN-LAST:event_jBdoisActionPerformed

    private void jBtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtresActionPerformed
        numeroDigitado("3");
    }//GEN-LAST:event_jBtresActionPerformed

    private void jBquatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBquatroActionPerformed
        numeroDigitado("4");
    }//GEN-LAST:event_jBquatroActionPerformed

    private void jBseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseisActionPerformed
        numeroDigitado("6");
    }//GEN-LAST:event_jBseisActionPerformed

    private void jBseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseteActionPerformed
        numeroDigitado("7");
    }//GEN-LAST:event_jBseteActionPerformed

    private void jBoitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoitoActionPerformed
        numeroDigitado("8");
    }//GEN-LAST:event_jBoitoActionPerformed

    private void jBnoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnoveActionPerformed
        numeroDigitado("9");
    }//GEN-LAST:event_jBnoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbsp;
    private javax.swing.JButton jBcinco;
    private javax.swing.JButton jBclr;
    private javax.swing.JButton jBdividir;
    private javax.swing.JButton jBdois;
    private javax.swing.JButton jBigual;
    private javax.swing.JButton jBmais;
    private javax.swing.JButton jBmenos;
    private javax.swing.JButton jBmm;
    private javax.swing.JButton jBnove;
    private javax.swing.JButton jBoito;
    private javax.swing.JButton jBponto;
    private javax.swing.JButton jBquatro;
    private javax.swing.JButton jBseis;
    private javax.swing.JButton jBsete;
    private javax.swing.JButton jBtres;
    private javax.swing.JButton jBum;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jBvezes;
    private javax.swing.JButton jBzero;
    private javax.swing.JTextField jTVisor;
    // End of variables declaration//GEN-END:variables
}
